FROM python:3.9.17

# set working directory
WORKDIR /app

# copying api backend resources
COPY /api .

# # install dependencies with pip
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY /sms_spam_clf.pkl .
COPY /sms.py .

# expose flask default port
EXPOSE 5000

# run flask app
CMD [ "flask", "--host", "0.0.0.0", "--port", "5000", "run" ]